// This file is generated by Slice Machine. Update with care!

import AboutMe from './AboutMe';
import Hero from './Hero';

export {
	AboutMe,
	Hero,
};

export const components = {
	about_me: AboutMe,
	hero: Hero,
};
