// This file is generated by Slice Machine. Update with care!

import AboutMe from './AboutMe';
import AboutSection from './AboutSection';
import FeaturedBlogPosts from './FeaturedBlogPosts';
import Hero from './Hero';
import SkillsSection from './SkillsSection';
import Tools from './Tools';

export {
	AboutMe,
	AboutSection,
	FeaturedBlogPosts,
	Hero,
	SkillsSection,
	Tools,
};

export const components = {
	about_me: AboutMe,
	about_section: AboutSection,
	featured_blog_posts: FeaturedBlogPosts,
	hero: Hero,
	skills_section: SkillsSection,
	tools: Tools,
};
